language: cpp
sudo: false
matrix:
  include:
  - os: linux
    language: pyhton
    env: PYTHON=2.7 CPP=11 GCC=4.8
    python: "2.7"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports]
        packages: [g++-4.8, cmake, pkg-config]
  - os: linux
    language: python
    env: PYTHON=3.4 CPP=11 GCC=4.8
    python: "3.4"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes]
        packages: [g++-4.8, cmake, pkg-config]

  - os: linux
    language: python
    env: PYTHON=3.5 CPP=11 GCC=4.8
    python: "3.5"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes]
        packages: [g++-4.8, cmake, pkg-config]
  - os: linux
    language: python
    env: PYTHON=3.6 CPP=11 GCC=4.8
    python: "3.6"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes]
        packages: [g++-4.8, cmake, pkg-config]

  - os: osx
    osx_image: xcode7.3
    env: PYTHON=2.7 CPP=14 CLANG
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=3.6 CPP=14 CLANG
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=3.5 CPP=14 CLANG
env:
  global:
  # - secure: QMtC7zYxU4pPwZrQ4OX2bjgPoei+2PYZPxuTOGewgI11HlbM7xFbryhloHeIeoeKXjKgUhCSY32lUiAP4NlT1ZkQVVr30m7FF+6hZkw6/bFvernOdr9kAd99Hg3uiunHCKoce7tTkIpo/eLTGAmr1Vbcc0FTZNagAWZmNClGOIw=
  # - secure: cKkW9x5L4KFuq3bzb9uCsYSiXo/V55m96Ua122Wo7J5BfiagJqXoPc8PcWwx/qgLrCiT2xzW4fTp1DFDq97LsaXxEp/TWvzI+zPhB4tfUDzF95Dbvkl7A+sgmmSYkBiD146WP4KjmMGEv65RzIS9nFaRikF1X790Sxy/pEAhjLY=
  - secure: DtbWE3aMH2wQTUm0goCGjmvX0UbKZWifyOlcEw0Wi3zTXboIFM84SZ6lWOnYKwOgA1gC/A94lwRdv6LTkLS/Kysj1PXYQl/qEr+1R2QllAQV3vSOGAU0jNW6DQOYeHNUqAGttRD53yiKpyrTXDfBQNEXxoOdpSjWVehrIXu8PToitM8Z67cEP4C/wafARhnSsXvjZTr48fZxrjwb6Tz2sWZ6HgdOWWwdl9+G0Fsf5ghfElAroW8zjOvMyU++ZfIdt9l+z2HzMSNl2ZhzhhRqiLovwxYrMypX0gZv4XUDNaIvEsWOCZsHyvBh4ccdLm/QDfP3R6YcUL1Lfxr+4FOR170ZGDMPwUGLJvNYA2audahzAWHsc61/ApycturU7aX1i2vR+MvywjV6OHTnsDxIoDLyu96jMAaVvOwfUI1Zk0vQWssuiA4rXpf4heCUFc5DZ7Xla0dUMX5ObfuSN1jOgbZJJAEnCxAiXOKUsnhhBPXzck69b6jjnHtXIhykzlD2BtNl0FKseT9ymQsW7zvBxUIzhU3h2NHdRHML73/0mdGPUfmBeTNNDSjF5nC2KECJ7LEBOYcmoGH2/UR5VlZwtSXwBwO9ikod3qkpmQ1VzJO6AFgtQl7U2VcKEna5oeHyqel4w0SQs2dwNzz5ETULp4T/ffO2er1sp3788yU3n+8=
  - secure: Wt1dAalRKv2B7ewmrtgxF5QngTB77jR+Q3kUVQuBkG5nL/+bK/h6bLjSbUVuR1tEu+T+M9+ClPq3PmHeZC7mbBAuwVEQB418+HGviVFy3W84ZgVYNAwrYRB1zfnkUaFoIwcOM4XUUU31aAr49RlS8Sl0DPWNDe31HCekiJpHu8xJuPVpRTlRtFjuRndBz6EvYUUwn4RhxvB6IPtxIzhiE22FnEFr3h2y4koEWygvmHha0PNEpReHqepzakFLoVDs6G4Q71MMmUcgOfVu9CV05Rzk9Pidtf2Mdiy2LnfDEckOeigMYPaEY59uWcFc+g9ZIxeOncYcL6mJ4TDCKIDCXhEMei3IaOXujs+PQ+9eG1hpM2PavKDHNTVadyaAKm+BDsgUvCDcuwkcocQWejKRb90vGGGUnQYFAutuManHcOI8Thiyp5xzM5Vtf/Q1g3QIStq46/WuHP/XxQYmfWLSrLPBmXP8WzWe0VQ4K/uGRXy3kGgDhyLFxfjPnhdPqtK0dK6q6qZDmM7BGlZVjiSwFTDyzEl7J951+0Jh8PRrxSrU3bJXjMCg5vcIqAKhHm24NtVBrpjIYvCk0vSDzFezXeFUPM4E0SIQHnPPo2Lk6GqirsJNGCHIjdnF4PFbbTxD4IdCmUBsMc0DhTmwn8IemPu1wfRP3N/euFFsl5pZNlg=
cache:
  directories:
  - $HOME/ibex
  - $HOME/Downloads

# matrix:
#   include:
#   - os: osx
#     compiler: clang
#   - os: linux
#     language: python
#     python: "3.4"
#     compiler: gcc-4.8
#   - os: linux
#     language: python
#     python: "3.5"
    # compiler: gcc-4.8

before_install:
  # - if [ $TRAVIS_OS_NAME == linux ]; then python -m pip install auditwheel twine; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install python3; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then pip install --user wheel twine; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew install clang-omp; fi
  - bash ./build_Ibex4pyIbex.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex
  - |
    # Configure build variables
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ -z "$GCC" ]; then export GCC=4.8; fi
      export CXX=g++-$GCC CC=gcc-$GCC;
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export CXX=clang++ CC=clang;
    fi
    if [ -n "$CPP" ]; then export CPP=-std=c++$CPP; fi
    if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        if [ "$PY" = "3" ]; then
          pip install --upgrade pip;
          pip install auditwheel twine pyibex;
        else
          pip install --user --upgrade pip;
          pip install --user auditwheel twine pyibex;
        fi
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ "$PY" = "3" ]; then
        brew update; brew install python$PY;
      else
        curl -fsSL -O https://bootstrap.pypa.io/get-pip.py;
        sudo -H python get-pip.py;
      fi
      pip$PY install --user --upgrade pip virtualenv auditwheel twine pyibex;
      python$PY -m virtualenv venv;
      source venv/bin/activate;
      pip install  --upgrade pip;
      pip install auditwheel twine pyibex;
    fi



# command to run tests
script:
  # - git clone -b build_process https://github.com/benEnsta/ibex-robotics.git ibex-robotics
  - mkdir build
  - cd build
  - ls ${HOME}/ibex
  - ls ${HOME}/ibex/lib

  - cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} -DPYBIND11_PYTHON_VERSION=$PYTHON -DPYBIND11_CPP_STANDARD=$CPP ../ ;
  - make

  - make test ARGS="-VV"
  - make pip_package
  - export wheel_file=$(ls *.whl)
  # - if [  $TRAVIS_OS_NAME == linux ]; then
      # auditwheel repair $(ls *.whl);
      # export wheel_file=$(ls wheelhouse/*.whl);
    # fi

  - mv $wheel_file $TRAVIS_BUILD_DIR/$wheel_file
after_failure: cat tests/test_cmake_build/*.log
after_success:
  - curl --ftp-create-dirs --ftp-ssl -p -k  -T $TRAVIS_BUILD_DIR/$wheel_file --user $FTP_USER:$FTP_PASSWD  ftp://bdesroch.homenet.org/gittmp/$(date +"%Y%m%d")/
# deploy:
#   skip_cleanup: true
#   provider: releases
#   api_key:
#     secure: PLxHkV8vz8cdPMQKOm6BDAPUZgScq3frcuWUQ0PVsB66gu2mW+tnvIQzg0duom7rv9wrOksblkAhLRh2kNh7coLnlAD5AT7Y74PUjYv6sFsv9Obh0Kvc97v4/7eVg4xOcdcvPYEiYCQ/ZfXPzpkOcUF7IRYx4KKXN9CbVpbU/W8=
#   file: $TRAVIS_BUILD_DIR/$wheel_file
#   prerelease: true
#   on:
#     overwrite: true
#     branch: master
#     tag: true
    # repo: benEnsta/pyIbex


# deploy:
#   provider: script
#   skip_cleanup: true
#   script: travis_script/deploy.sh
#   on:
#     branch: appveyor
#     tag: false

#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#    secure: CuUogABlVRxUKWchoCT9PI7YwEmTRBhSjTEx+8Vi5HAb9Eq4nAR+Nc3bMHM0mSmxZn9lDGTjWDOMOdpg8nw80rZi1mCepO3fYa2eVrK6YlFIvZNLbAx2u4MUCXTYmsurpUiV7Du8LSbKA942y0RDCOX27pCyDCO5jfSOj7xlQWOgoryxfjFwsuBQntHMCWp/AH1HxlmJ40KZgQl4Nha2xuIJPBt2fYSBkjsWot0nd1hVhDUFxgi7zzOMAzC+vYrdmo89EVb4PfMPDlc+2LHnT7MMo7T7KrG1muRAryoOqsVsUfKXP9QUjGzpcjNKKimhB1ZikS/3ncEpQtO4/60TUY+cUJcw/22Idn5iReBnME21kpNUxiN7PvhirAs5g9Yic2f0uCIsLHXeqSWOTkwHZKyyyPKsDH/0/0SFYSihPawPOwqUPujLBAkIeHRf1REgsWyAFgxoSEgIs8r5/8Buj8ow7Ho/kR/QTJ5IZpgg806EOd8yxMa9C4H9LprK0J9el/pOFrgYBreQjTrxNyQhnnLSqUEumkH7atG5RRRW4pUCFMtO3pJp7EvgCWgFYlxU7NXLsjTcoNE6Juhu1RrkAdbpya90FqSobQ//cmaidMZNqqwbimH7XtUPO1iS/OuselmbcgsnD3QzgMwP0V4+XWfgWdg4On9QTUG/CS0LWec=
#  file: $TRAVIS_BUILD_DIR/$wheel_file
#  on:
#    repo: benEnsta/pyIbex
#    tags: true
